### ISSUE TITLE
Patched poppler libraries not used by Okular/Evince

### ISSUE THREAD

**Issue by schickele** [jonathanffon/poppler-lcd-patch#1]
Thank you very much for this patch. I'm looking forward to using Okular with subpixel rendering since I switched to Linux. I cannot understand why this doesn't come with those PDF viewers out of the box.

I followed your instructions to compile and install `poppler-0.76.0` on my system (Kde Neon based on Ubuntu 18.04). Unfortunately, both Okular and Evince seem to ignore the new poppler libraries. Is there a way to enforce this?

I've also tried your patch on Arch Linux via the `yay` command. Same result there: Okular and Evince do not use the patched poppler version. Sorry if this is a novice question.

**Comment by jonathanffon** [comment]
I encountered the same problem before. You may have another version of `libpoppler.so` in `/usr/lib`.
At first, I try to integrate patched poppler library to every application that uses it. Obviously, it's a bad idea and involves some tedious patches. You can navigate to https://aur.archlinux.org/packages/evince-lcd-standalone to see my previous work.
Forcing Okular or Evince to use a specified patched poppler means those applications have to be patched as well... So I turn to patching the default `poppler` directly.
After you replace the default `poppler` with the one generated by this repo, the subpixel engine will work properly.
